# Generated by Django 5.1.3 on 2024-12-05 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image_url', models.TextField()),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
