# Generated by Django 5.1.3 on 2024-12-05 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
