# Generated by Django 5.1.3 on 2024-12-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
