# Generated by Django 5.1.3 on 2024-12-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_url',
            field=models.SlugField(default=''),
        ),
    ]
