# Generated by Django 5.1.3 on 2024-12-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0006_product_seo_title_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.SlugField(default='', editable=False),
        ),
    ]
