# Generated by Django 5.1.3 on 2024-12-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0011_alter_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
