# Generated by Django 5.1.3 on 2024-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0013_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.TextField(null=True),
        ),
    ]
