# Generated by Django 5.1.3 on 2024-12-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0014_alter_product_category_alter_product_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
