# Generated by Django 5.1.3 on 2024-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
