# Generated by Django 5.1.3 on 2024-12-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0019_newproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
