# Generated by Django 5.1.3 on 2024-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0020_delete_newproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.SlugField(default='', editable=False, max_length=2000, unique=True),
        ),
    ]
