# Generated by Django 5.1.3 on 2024-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molasses', '0021_alter_product_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
